name: remove-repo-access-from-teams
on:
  workflow_dispatch:
    inputs:
      organization:
        type: string
        default: 'devwithkrishna'
        description: "The GitHub organization where the team will be provided access to."
        required: true
      team_name:
        description: "The name of the github team."
        type: string
        required: true
      repo_names:
        description: "repositories to be added to the teams"
        required: true
      

run-name: ${{ github.actor }} - removing access from -${{ inputs.team_name }} - ${{inputs.repo_names}}
jobs:
  remove-repo-access-from-teams:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: execute the program
        env:
          GH_TOKEN: ${{ secrets.DEVWITHKRISHNA_PERSONAL_ACCESS_TOKEN }}
        run: |
          bash remove_repo_access_from_teams.sh "${{ inputs.organization }}" "${{ inputs.team_name }}" "${{ inputs.repo_names }}"

  
